version: '3.5'
services:
  Weatherforecase.Service:
   image: ssldemo
   build:
    context: ./HTTPSCertDemo
    dockerfile: Dockerfile
   environment: 
    - ASPNETCORE_ENVIRONMENT=Development
    - ASPNETCORE_URLS=https://+:443;http://+:80
    - ASPNETCORE_Kestrel__Certificates__Default__Password=password
    - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
   ports:
    - "8081:80"
    - "8082:443"
   volumes:
    - ~/.aspnet/https:/https:ro